---
- name: Install and start apache web server
  hosts: web
  become: yes
  gather_facts: false
  vars:
    httpd_packages:
      - httpd
      - vim
      - wget
    index_file_name: /var/www/html/index.html

  tasks:
    - name: install apache
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ httpd_packages }}"
      
    - name: start apache
      service:
        name: httpd
        state: started

    - name: Populate index file
      shell: echo "Hello world `date`" >> {{ index_file_name }}
      changed_when: false

    - name: Display content of index file
      shell: cat {{ index_file_name }}
      changed_when: false
      register: cat_index_cmd_output


    - debug:
        var: cat_index_cmd_output.stdout_lines
