---
- name: Install and start apache web server
  hosts: web
  become: yes
  gather_facts: false
  vars:
    httpd_packages: httpd

  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present
      notify: restart apache service

    - name: Populate index file
      shell: echo "Hello world `date`" > /var/www/html/index.html
      notify: restart apache service
      changed_when: false

    - name: start apache
      service:
        name: httpd
        state: started
        enabled: yes     

  handlers:
    - name: restart apache service
      service:
        name: httpd
        state: restarted